name: Release Dofus 2 Main Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version that will be downloaded
        required: true

jobs:
    build:
        runs-on: self-hosted
        steps:
        -   
            name: Set up Python for lastversion
            run: sudo apt-get install curl python3 python3-pip python3-setuptools python3-wheel -y
        -  
            name: Get doduda
            run: |
                python3 -m pip install lastversion
                docker pull stelzo/doduda:latest
                curl -s https://api.github.com/repos/dofusdude/doduda/releases/latest \
                | grep "browser_download_url.*Linux_arm64.tar.gz" \
                | cut -d : -f 2,3 \
                | tr -d \" \
                | wget -qi -
                tar -xzf doduda_Linux_arm64.tar.gz
                chmod +x doduda
        -
            name: Download data from Ankama servers
            run: docker run --rm -it -v $PWD/data:/app/data stelzo/doduda:latest --python $(which python3)
        -
            name: Map to application usable format
            run: |
                mkdir persistent
                curl -o persistent/elements.json -L https://raw.githubusercontent.com/dofusdude/doduda/main/persistent/elements.json
                curl -o persistent/item_types.json -L https://raw.githubusercontent.com/dofusdude/doduda/main/persistent/item_types.json
                ./doduda parse --dir $PWD
        -
            name: Group images
            run: |
                tar -czf items_images.tar.gz data/img/item/
                tar -czf mounts_images.tar.gz data/img/mount/

                tar -czf items_images_vector.tar.gz data/vector/item/
                tar -czf mounts_images_vector.tar.gz data/vector/mount/
        - 
            name: Upload release assets
            uses: "marvinpinto/action-automatic-releases@latest"
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              prerelease: false
              title: "Dofus 2 main ${{ github.event.inputs.version }}" 
              files: |
                data/*.json
                data/languages/*.json
                items_images.tar.gz
                mounts_images.tar.gz
                items_images_vector.tar.gz
                mounts_images_vector.tar.gz
                