name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version that will be downloaded
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ github.event.inputs.version }}"
  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: System dependencies
        run: sudo apt-get install curl wget -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download assets
        run: ./download.sh
      - name: Upload assets
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ github.event.inputs.version }}"
          automatic_release_tag: "${{ github.event.inputs.version }}"
          files: out/*
      - name: Notify doduapi to update
        run: |
          curl -X POST \
          https://api.dofusdu.de/dofus2/update/${{ secrets.DODUAPI_TOKEN }} \
          -d '{"version":"${{ github.event.inputs.version }}"}'
