name: release

on:
    workflow_dispatch:
      inputs:
        version:
          type: string
          description: The version that will be downloaded
          required: true

jobs:
    tag:
        runs-on: ubuntu-20.04
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        - 
            name: Tag snapshot
            uses: tvdias/github-tagger@v0.0.1
            with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                tag: "${{ github.event.inputs.version }}"
    release:
        needs: tag
        runs-on: ubuntu-latest
        steps:
        -   
            name: System dependencies
            run: sudo apt-get install curl -y
        -  
            name: Get doduda
            run: |
                curl -s https://api.github.com/repos/dofusdude/doduda/releases/latest \
                | grep "browser_download_url.*Linux_x86_64.tar.gz" \
                | cut -d : -f 2,3 \
                | tr -d \" \
                | wget -qi -
                tar -xzf doduda_Linux_x86_64.tar.gz
                chmod +x doduda
        -
            name: Get data
            run: |
                docker pull stelzo/swf-renderer:latest
                sudo ./doduda --headless
                sudo ./doduda map --headless --indent
        -
            name: Images
            run: |
                tar -czf items_images.tar.gz data/img/item/
                tar -czf mounts_images.tar.gz data/img/mount/

                tar -czf items_images_vector.tar.gz data/vector/item/
                tar -czf mounts_images_vector.tar.gz data/vector/mount/

                sudo mkdir -p data/vector/mount
                sudo mkdir -p data/img/mount
                sudo ./doduda render data/vector/mount data/img/mount 200 --headless --incremental dofusdude/dofus2-main/mounts_images_200
                tar -czf mounts_images_200.tar.gz $( find data/img/mount -name "*-200.png" )

                sudo ./doduda render data/vector/mount data/img/mount 400 --headless --incremental dofusdude/dofus2-main/mounts_images_400
                tar -czf mounts_images_400.tar.gz $( find data/img/mount -name "*-400.png" )

                sudo ./doduda render data/vector/mount data/img/mount 800 --headless --incremental dofusdude/dofus2-main/mounts_images_800
                tar -czf mounts_images_800.tar.gz $( find data/img/mount -name "*-800.png" )

                sudo mkdir -p data/vector/item
                sudo mkdir -p data/img/item
                sudo ./doduda render data/vector/item data/img/item 200 --headless --incremental dofusdude/dofus2-main/items_images_200
                tar -czf items_images_200.tar.gz $( find data/img/item -name "*-200.png" )

                sudo ./doduda render data/vector/item data/img/item 400 --headless --incremental dofusdude/dofus2-main/items_images_400
                tar -czf items_images_400.tar.gz $( find data/img/item -name "*-400.png" )

                sudo ./doduda render data/vector/item data/img/item 800 --headless --incremental dofusdude/dofus2-main/items_images_800
                tar -czf items_images_800.tar.gz $( find data/img/item -name "*-800.png" )
        -
            name: Upload assets
            uses: "marvinpinto/action-automatic-releases@latest"
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              prerelease: false
              title: "${{ github.event.inputs.version }}"
              automatic_release_tag: "${{ github.event.inputs.version }}"
              files: |
                data/*.json
                data/languages/*.json
                items_images.tar.gz
                items_images_200.tar.gz
                items_images_400.tar.gz
                items_images_800.tar.gz
                mounts_images.tar.gz
                mounts_images_200.tar.gz
                mounts_images_400.tar.gz
                mounts_images_800.tar.gz
                items_images_vector.tar.gz
                mounts_images_vector.tar.gz
        -
            name: Notify doduapi to update
            run: |
                curl -X POST \
                https://api.dofusdu.de/dofus2/update/${{ secrets.DODUAPI_TOKEN }} \
                -d '{"version":"${{ github.event.inputs.version }}"}'
